# Generated by Django 3.2.5 on 2022-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='mode',
            field=models.ManyToManyField(blank=True, default='新進案', to='case.Mode'),
        ),
    ]
