# Generated by Django 3.2.7 on 2022-02-12 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
    ]
