# Generated by Django 3.2.5 on 2022-01-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='mode',
            field=models.ManyToManyField(default='新進案', to='case.Mode'),
        ),
    ]
