# Generated by Django 3.2.5 on 2022-01-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_case_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='mode',
            field=models.ManyToManyField(to='case.Mode'),
        ),
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.ForeignKey(default='新進案', null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.state'),
        ),
    ]
