# Generated by Django 3.2.5 on 2022-01-21 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20220121_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updatedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
