# Generated by Django 3.2.7 on 2022-01-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_email'),
        ('case', '0006_case_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='mode',
            field=models.ManyToManyField(blank=True, to='case.Mode'),
        ),
        migrations.AlterField(
            model_name='case',
            name='respondent',
            field=models.ManyToManyField(blank=True, to='user.Respondent'),
        ),
    ]
