# Generated by Django 3.2.7 on 2022-01-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20220122_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='mode',
            field=models.ManyToManyField(blank=True, to='case.Mode'),
        ),
    ]
